#!/bin/bash

kubectl patch felixconfiguration.p default -p '{"spec":{"flowLogsFlushInterval":"10s"}}'
kubectl patch felixconfiguration.p default -p '{"spec":{"dnsLogsFlushInterval":"10s"}}'
kubectl patch felixconfiguration.p default -p '{"spec":{"flowLogsFileAggregationKindForAllowed":1}}'

# Deploy compliance reports 
kubectl apply -f https://raw.githubusercontent.com/JosephYostos/Compliance-workshop/main/04-Reports-Visualization/%20mainfest/daily-cis-results.yaml
kubectl apply -f https://raw.githubusercontent.com/JosephYostos/Compliance-workshop/main/04-Reports-Visualization/%20mainfest/cluster-reports.yaml