#!/bin/bash

#breaking the frontend policy by blocking ingress
kubectl replace -f https://raw.githubusercontent.com/JosephYostos/test-repo/main/manifest/break-frontend.yaml


# Deploy compliance reports 
kubectl apply -f https://raw.githubusercontent.com/JosephYostos/Compliance-workshop/main/04-Reports-Visualization/%20mainfest/daily-cis-results.yaml
kubectl apply -f https://raw.githubusercontent.com/JosephYostos/Compliance-workshop/main/04-Reports-Visualization/%20mainfest/cluster-reports.yaml