version: "3"
virtualmachines:
- name: controlplane
  image: tigera-marketing/ubuntu-15gb-noautoupdate
  shell: /bin/bash
  machine_type: n1-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: node01
  image: tigera-marketing/ubuntu-15gb-noautoupdate
  shell: /bin/bash
  machine_type: n1-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
