#!/bin/bash 

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Wait for the Kubernetes API server to become available
#while ! curl --silent --fail --output /dev/null http://localhost:8001/api 
#do
#    sleep 1 
#done

# Enable bash completion for kubectl
#echo "complete -F __start_kubectl k" >> /root/.bashrc
#echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc

# install Kubeadm 
curl https://raw.githubusercontent.com/JosephYostos/kubeadm-installation/main/master.sh |bash

#export token
kubeadm token list | awk 'NR == 2 {print $1}' > /token

# install calico CNI
kubectl create -f https://projectcalico.docs.tigera.io/archive/v3.22/manifests/tigera-operator.yaml
kubectl create -f https://projectcalico.docs.tigera.io/archive/v3.22/manifests/custom-resources.yaml


